Phase 1b: Shaka Lab Node for Linux
shaka-project/shaka-lab pull request #3
Opened 2022-11-09 01:13 UTC by joeyparrish

2022-11-09 02:47 UTC, joeyparrish commented on shaka-lab-node/linux/debian/shaka-lab-node.postinst
> +# Install NVM, which we don't / shouldn't bundle into the deb package.
It's disappointing to have to do this, but even the LTS Ubuntu release from earlier this year only ships Node v12, which was already 2 years old when that version of Ubuntu was released.  So even with this year's Ubuntu LTS, we can't depend on a packaged version of nodejs.  And we also don't want to limit this package to fresh versions of Ubuntu.  So NVM seems like a good escape hatch.

I'm open to other options, though, if you have any suggestions.

2022-11-15 13:38 UTC, theodab requested changes

2022-11-15 13:38 UTC, theodab commented on shaka-lab-node/linux/debian/shaka-lab-node.postinst
> +# Install NVM, which we don't / shouldn't bundle into the deb package.
I'm not knowledgeable enough about this kind of thing to make any good suggestions, I don't think.

2022-11-15 13:38 UTC, theodab commented on shaka-lab-node/node-templates.yaml
> +    genericwebdriver.backend.exe: node_modules/.bin/xbox-one-webdriver-server$cmd
It's probably better this way for the sake of consistency, but strictly speaking you could just write `.cmd` here, right?
Since Xbox One tests need to be run on Windows, as per the readme.

2022-11-15 13:38 UTC, theodab commented on shaka-lab-node/start-nodes.js
> +let configPath = '/etc/shaka-lab-node-config.yaml';
I assume these values will be set to something else on other platforms, once you add support for them in later phases of this process? As-is, they are all defined by `let` but none of them are ever changed.

2022-11-15 13:38 UTC, theodab commented on shaka-lab-node/start-nodes.js
> +
Some basic JSDoc for these functions could be helpful for making sure that this code is readable.

2022-11-15 13:38 UTC, theodab commented on shaka-lab-node/start-nodes.js
> +function loadTemplate(templates, templateName) {
I think `getTemplate` would be a more accurate name. The templates are already loaded from the file system by the time this function is called.

2022-11-18 00:17 UTC, joeyparrish commented on shaka-lab-node/node-templates.yaml
> +    genericwebdriver.backend.exe: node_modules/.bin/xbox-one-webdriver-server$cmd
Yes, that's true.

2022-11-18 00:18 UTC, joeyparrish commented on shaka-lab-node/start-nodes.js
> +let configPath = '/etc/shaka-lab-node-config.yaml';
Yes, exactly right.  I have it working for all platforms in the `dev` branch, so when I split the work up into more reviewable chunks, it stayed "let".  It gets an alternate value in the next PR.

2022-11-18 00:19 UTC, joeyparrish commented on shaka-lab-node/start-nodes.js
> +function loadTemplate(templates, templateName) {
Good point.  Changed.

2022-11-18 00:34 UTC, joeyparrish commented on shaka-lab-node/start-nodes.js
> +
Done.  I hope that helps!

2022-11-18 00:35 UTC, joeyparrish commented on shaka-lab-node/linux/debian/shaka-lab-node.postinst
> +# Install NVM, which we don't / shouldn't bundle into the deb package.
No worries.  Just putting it out there in recognition of the compromise I had to make on Linux.

2022-11-18 22:58 UTC, alekzz approved these changes

2022-11-18 23:22 UTC, theodab approved these changes

2022-11-18 23:25 UTC, merged